services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\ServiceProvider\ServiceProvider: ~

  # Прямой алиас сервис-контейнера Symfony. @service_container - deprecated.
  Psr\Container\ContainerInterface: '@service_container'

  #############
  # Wordpress
  #############
  # Регистратор кастомных типов постов.
  custom.post.type.registrator:
    class: Prokl\ServiceProvider\Services\PostTypes\PostTypeRegistrator
    tags:
      - { name: 'post.type.registrator'}

  Prokl\ServiceProvider\Services\PostTypes\PostTypeRegistrator: '@custom.post.type.registrator'