services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\ServiceProvider\ServiceProvider: ~

  # Прямой алиас сервис-контейнера Symfony. @service_container - deprecated.
  Psr\Container\ContainerInterface: '@service_container'
  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

  # Ядро.
  Symfony\Component\HttpKernel\KernelInterface: '@kernel'
  Symfony\Component\HttpKernel\Kernel: '@kernel'

  # Параметры приложения.
  parameter_bag:
    class: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
    arguments: ["@service_container"]

  # Параметры приложения. Алиас.
  Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface: '@parameter_bag'
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@parameter_bag'

  # Запрос.
  app.request:
    class: Prokl\ServiceProvider\Services\AppRequest
    tags: ['service.bootstrap']

  Prokl\ServiceProvider\Services\AppRequest: '@app.request'
  request: '@app.request'

  # Request приложения.
  global.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: ['@app.request', 'getRequest']

  # Текущий URL.
  app.request.uri:
    class: Prokl\ServiceProvider\Services\AppRequest
    factory: ['@app.request', 'getRequestUri']

  #############
  # Wordpress
  #############

  # Регистратор кастомных типов постов.
  custom.post.type.registrator:
    class: Prokl\ServiceProvider\Services\PostTypes\PostTypeRegistrator
    tags:
      - { name: 'post.type.registrator'}

  Prokl\ServiceProvider\Services\PostTypes\PostTypeRegistrator: '@custom.post.type.registrator'


  controller_resolver:
    class: Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver
    arguments: ['@service_container']

  Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver: '@controller_resolver'

  argument_metadata_factory:
    class: Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory

  Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory: '@argument_metadata_factory'

  argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver
    arguments:
      - '@argument_metadata_factory'
      - [
        '@argument_resolver.request_attribute',
        '@argument_resolver.session',
        '@argument_resolver.service',
        '@argument_resolver.default',
        '@argument_resolver.variadic',
      ]

  Symfony\Component\HttpKernel\Controller\ArgumentResolver: '@argument_resolver'

  argument_resolver.request_attribute:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 100}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver: '@argument_resolver.request_attribute'

  argument_resolver.request:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver: '@argument_resolver.request'

  argument_resolver.session:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver: '@argument_resolver.session'

  argument_resolver.service:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver: '@argument_resolver.service'

  argument_resolver.default:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver: '@argument_resolver.default'

  argument_resolver.variadic:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver: '@argument_resolver.variadic'


